[project]
name = "langchain-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "javedemailsignet-commits", email = "javedemailsignet@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "langchain>=1.4.2",
    "langchain-ollama>=1.1.0",
]

[project.scripts]
langchain-demo = "langchain_demo:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
